//@version=4
study("双均线交易策略", overlay=true)



fastPeriod = input(title="快线",defval=12,type=input.integer,minval=3)
slowtPeriod = input(title="慢线",defval=26,type=input.integer,minval=3)


fastSma = sma(close,fastPeriod)
slowSma = sma(close,slowtPeriod)

fastOver=crossover(close[fastSma],close[slowSma])
fastUnder=crossunder(close[fastSma],close[slowSma])

plot(fastSma,color=color.teal)
plot(slowSma,color=color.red)